import React from 'react';

import '../style/globals.scss';
import type { Metadata } from 'next';
import { Layout } from '@/components';
import { SidebarToggleProvider } from '@/providers/SidebarToggleProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SidebarToggleProvider>
          <Layout>
            {children}
          </Layout>
        </SidebarToggleProvider>
      </body>
    </html>
  );
}
